spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:my_local_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.pioli.users.infra.messaging.configuration.DomainEventSerializer
      properties:
        spring.json.add.type.headers: false
    topic:
      user-created: users
      orders: orders
server:
  servlet:
    context-path: /v1
logging:
  level:
    root: ERROR
    # org.apache.kafka: DEBUG
    # org.springframework.kafka: DEBUG
    # org.springframework.kafka.support.serializer: TRACE
    # com.pioli.users.infra.messaging: TRACE
